version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    container_name: task-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/tasks"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [tasks-net]

  web:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: task-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [tasks-net]

networks:
  tasks-net:
    driver: bridge
