name: SubBranchCI

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: subbranchci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: s1natex/my-devops-cicd-demo
  DEPLOYMENT_FILE: k8s/deployment.yaml

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, '[skip-subbranchci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            app/requirements.txt
            requirements-dev.txt

      - name: Install deps
        run: pip install -r app/requirements.txt -r requirements-dev.txt

      - name: Unit + Integration tests
        env:
          PYTHONPATH: .
        run: pytest tests/unit tests/integration -q

  build_and_push:
    if: ${{ !contains(github.event.head_commit.message, '[skip-subbranchci]') }}
    needs: tests
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.meta.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        id: meta
        shell: bash
        run: |
          DATE=$(date +%Y%m%d)
          SHA=${GITHUB_SHA::7}
          BRANCH_SLUG=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g' | sed 's/^-*//; s/-*$//' | cut -c1-40)
          echo "TAG=${BRANCH_SLUG}-${DATE}-${SHA}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t $IMAGE:${{ steps.meta.outputs.TAG }} ./app

      - name: Push image
        run: docker push $IMAGE:${{ steps.meta.outputs.TAG }}

  update_manifests_commit_only:
    if: ${{ !contains(github.event.head_commit.message, '[skip-subbranchci]') }}
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}   # the original sub-branch

      - name: Configure git
        run: |
          git config user.name  "ManifestUpdater[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update local branch (rebase first)
        run: |
          git fetch origin "${GITHUB_REF_NAME}"
          # ensure we're tracking the remote branch and are up to date
          git checkout -B "${GITHUB_REF_NAME}" "origin/${GITHUB_REF_NAME}"
          git pull --rebase origin "${GITHUB_REF_NAME}"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update deployment image tag
        env:
          IMG:  ${{ env.IMAGE }}
          TAG:  ${{ needs.build_and_push.outputs.TAG }}
          FILE: ${{ env.DEPLOYMENT_FILE }}
        run: |
          yq -i '.spec.template.spec.containers |= map(.image = strenv(IMG) + ":" + strenv(TAG))' "$FILE"

      - name: Commit manifest bump (skip CI loop)
        run: |
          git add "$DEPLOYMENT_FILE"
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "[skip-subbranchci] chore(k8s): bump image to $IMAGE:${{ needs.build_and_push.outputs.TAG }}"

      - name: Push back to same branch (retry on race)
        run: |
          set -e
          if git push --no-verify origin "HEAD:${GITHUB_REF_NAME}"; then
            exit 0
          fi
          echo "Push rejected, rebasing onto latest and retrying..."
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push --no-verify origin "HEAD:${GITHUB_REF_NAME}"
