name: ci
on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]
jobs:
  tests-unit-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: pip install -r app/requirements.txt -r requirements-dev.txt
      - name: Unit + Integration tests
        run: pytest tests/unit tests/integration -q
