name: PRCI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: prci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-unit-integration-PR:
    # Skip for draft PRs; remove this 'if' to test drafts too
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            app/requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: pip install -r app/requirements.txt -r requirements-dev.txt

      - name: Run unit + integration tests
        env:
          PYTHONPATH: .
        run: pytest tests/unit tests/integration -q
